# Generated by Django 5.1.9 on 2025-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('hd_type', models.IntegerField()),
                ('atk_as', models.FloatField()),
                ('fortitude', models.CharField(max_length=4)),
                ('reflex', models.CharField(max_length=4)),
                ('will', models.CharField(max_length=4)),
                ('skill_points', models.IntegerField()),
                ('number_of_feats', models.IntegerField()),
            ],
        ),
    ]
