# Generated by Django 5.1.9 on 2025-05-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
