# Generated by Django 5.1.9 on 2025-06-03 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0002_monster'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='monstertype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='monsterbuilder.monstertype'),
            preserve_default=False,
        ),
    ]
