# Generated by Django 5.1.9 on 2025-06-10 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0003_monster_monstertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='monster',
            name='constitution',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='monster',
            name='dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='monster',
            name='hd_number',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='monster',
            name='size',
            field=models.IntegerField(choices=[(-8, 'Colossal'), (-4, 'Gargantuan'), (-2, 'Huge'), (-1, 'Large'), (0, 'Medium'), (1, 'Small'), (2, 'Tiny'), (4, 'Diminutive'), (8, 'Fine')], null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='speed',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='monster',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='monster',
            name='wisdom',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monstertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='monsterbuilder.monstertype'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('modifier', models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma')], max_length=3)),
                ('synergy', models.ManyToManyField(related_name='synergy_provider', to='monsterbuilder.skill')),
            ],
        ),
    ]
