# Generated by Django 5.1.9 on 2025-06-10 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0005_alter_skill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranks', models.IntegerField()),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsterbuilder.monster')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsterbuilder.skill')),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='skills',
            field=models.ManyToManyField(through='monsterbuilder.SkillRanks', to='monsterbuilder.skill'),
        ),
    ]
