# Generated by Django 5.1.9 on 2025-06-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0006_skillranks_monster_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.IntegerField(choices=[(-8, 'Colossal'), (-4, 'Gargantuan'), (-2, 'Huge'), (-1, 'Large'), (0, 'Medium'), (1, 'Small'), (2, 'Tiny'), (4, 'Diminutive'), (8, 'Fine')])),
                ('damage', models.CharField(max_length=10)),
                ('atk_form', models.CharField(max_length=6)),
                ('proficiency', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='fortitude',
            field=models.CharField(default='null', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='reflex',
            field=models.CharField(default='null', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='will',
            field=models.CharField(default='null', max_length=4),
            preserve_default=False,
        ),
    ]
