# Generated by Django 5.1.9 on 2025-06-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0007_weapon_monster_fortitude_monster_reflex_monster_will'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='size',
            field=models.IntegerField(choices=[('C', 'Colossal'), ('G', 'Gargantuan'), ('H', 'Huge'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small'), ('T', 'Tiny'), ('D', 'Diminutive'), ('F', 'Fine')], null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='size',
            field=models.IntegerField(choices=[('C', 'Colossal'), ('G', 'Gargantuan'), ('H', 'Huge'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small'), ('T', 'Tiny'), ('D', 'Diminutive'), ('F', 'Fine')]),
        ),
    ]
