# Generated by Django 5.1.9 on 2025-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0008_alter_monster_size_alter_weapon_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='speed_burrow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='speed_climb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='speed_fly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='speed_swim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='hd_number',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monster',
            name='size',
            field=models.IntegerField(choices=[(-8, 'Colossal'), (-4, 'Gargantuan'), (-2, 'Huge'), (-1, 'Large'), (0, 'Medium'), (1, 'Small'), (2, 'Tiny'), (4, 'Diminutive'), (8, 'Fine')], default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='size',
            field=models.IntegerField(choices=[(-8, 'Colossal'), (-4, 'Gargantuan'), (-2, 'Huge'), (-1, 'Large'), (0, 'Medium'), (1, 'Small'), (2, 'Tiny'), (4, 'Diminutive'), (8, 'Fine')]),
        ),
    ]
