# Generated by Django 5.1.9 on 2025-06-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0009_monster_speed_burrow_monster_speed_climb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstertype',
            name='base_number_of_feats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monstertype',
            name='base_skill_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
