# Generated by Django 5.1.9 on 2025-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0010_monstertype_base_number_of_feats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=6)),
                ('armor_bonus', models.IntegerField()),
                ('max_dex', models.IntegerField()),
                ('armor_penalty', models.IntegerField()),
                ('arcane_failure', models.IntegerField()),
            ],
        ),
    ]
