# Generated by Django 5.1.9 on 2025-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0011_armor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='max_dex',
            field=models.IntegerField(null=True),
        ),
    ]
