# Generated by Django 5.1.9 on 2025-07-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0012_alter_armor_max_dex'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='manufactured_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='monsterbuilder.armor'),
        ),
        migrations.AddField(
            model_name='monster',
            name='natural_armor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='speed_fly_maneuverability',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='monster',
            name='size',
            field=models.IntegerField(choices=[(-8, 'colossal'), (-4, 'gargantuan'), (-2, 'huge'), (-1, 'large'), (0, 'medium'), (1, 'small'), (2, 'tiny'), (4, 'diminutive'), (8, 'fine')], default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='speed_burrow',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='speed_climb',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='speed_fly',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='speed_swim',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='size',
            field=models.IntegerField(choices=[(-8, 'colossal'), (-4, 'gargantuan'), (-2, 'huge'), (-1, 'large'), (0, 'medium'), (1, 'small'), (2, 'tiny'), (4, 'diminutive'), (8, 'fine')]),
        ),
    ]
