# Generated by Django 5.1.9 on 2025-07-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0013_monster_manufactured_armor_monster_natural_armor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='skillranks',
            name='racial_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skillranks',
            name='ranks',
            field=models.IntegerField(default=0),
        ),
    ]
