# Generated by Django 5.1.9 on 2025-07-28 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0014_specialabilities_skillranks_racial_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prerequisite', models.JSONField(default=None)),
                ('has_detail', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='attacks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='FeatDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(default='')),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsterbuilder.feat')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsterbuilder.monster')),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='feats',
            field=models.ManyToManyField(through='monsterbuilder.FeatDetails', to='monsterbuilder.feat'),
        ),
    ]
