# Generated by Django 5.1.9 on 2025-07-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0015_feat_monster_attacks_featdetails_monster_feats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feat',
            name='prerequisite',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
