# Generated by Django 5.1.9 on 2025-07-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0016_alter_feat_prerequisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='SpecialAbilities',
        ),
        migrations.AlterField(
            model_name='armor',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='name',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
