# Generated by Django 5.1.9 on 2025-07-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0017_specialability_delete_specialabilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
