# Generated by Django 5.1.9 on 2025-07-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0019_alter_weapon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialability',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='skill',
            name='synergy',
            field=models.ManyToManyField(blank=True, related_name='synergy_provider', to='monsterbuilder.skill'),
        ),
    ]
