# Generated by Django 5.1.9 on 2025-07-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0020_specialability_summary_alter_skill_synergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialability',
            name='attack_or_quality',
            field=models.CharField(default='attack', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialability',
            name='save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialability',
            name='save_ability',
            field=models.CharField(blank=True, choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='specialability',
            name='save_effect',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='specialability',
            name='save_type',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='specialability',
            name='summary',
            field=models.BooleanField(default=False),
        ),
    ]
