# Generated by Django 5.1.9 on 2025-07-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0021_specialability_attack_or_quality_specialability_save_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialability',
            name='save',
        ),
    ]
