# Generated by Django 5.1.9 on 2025-07-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0022_remove_specialability_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstertype',
            name='monster_special_abilities',
            field=models.ManyToManyField(to='monsterbuilder.specialability'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='fortitude',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('open', 'Open')], max_length=4),
        ),
        migrations.AlterField(
            model_name='monster',
            name='reflex',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('open', 'Open')], max_length=4),
        ),
        migrations.AlterField(
            model_name='monster',
            name='will',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('open', 'Open')], max_length=4),
        ),
        migrations.AlterField(
            model_name='specialability',
            name='save_effect',
            field=models.CharField(blank=True, choices=[('negates', 'Negates'), ('halves', 'Halves')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='specialability',
            name='save_type',
            field=models.CharField(blank=True, choices=[('FORT', 'Fortitude'), ('REF', 'Reflex'), ('WILL', 'Will')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='atk_form',
            field=models.CharField(choices=[('melee', 'Melee'), ('ranged', 'Ranged'), ('thrown', 'Thrown')], max_length=6),
        ),
    ]
