# Generated by Django 5.1.9 on 2025-08-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0023_monstertype_monster_special_abilities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialability',
            name='attack_or_quality',
        ),
        migrations.AddField(
            model_name='specialability',
            name='category',
            field=models.CharField(choices=[('attack', 'Attack'), ('immunity', 'Immunity'), ('resistance', 'Resistance'), ('vulnerability', 'Vulnerability'), ('sense', 'Sense'), ('quality', 'Quality')], default='quality', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='fortitude',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('open', 'Open')], max_length=4),
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='reflex',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('open', 'Open')], max_length=4),
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='will',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('open', 'Open')], max_length=4),
        ),
    ]
