# Generated by Django 5.1.9 on 2025-08-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0024_remove_specialability_attack_or_quality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialability',
            name='summary',
        ),
        migrations.AddField(
            model_name='monster',
            name='advancement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='alignment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='challenge_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='climate',
            field=models.CharField(choices=[('any', 'Any'), ('cold', 'Cold'), ('temp', 'Temperate'), ('warm', 'Warm')], default='Any', max_length=4),
        ),
        migrations.AddField(
            model_name='monster',
            name='monster_appearance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='monster_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='organization',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='plane',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='shield',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='terrain',
            field=models.CharField(choices=[('any', 'Any'), ('aquatic', 'Aquatic'), ('deserts', 'Deserts'), ('forests', 'Forests'), ('hills', 'Hills'), ('marshes', 'Marshes'), ('mountains', 'Mountains'), ('plains', 'Plains'), ('underground', 'Underground')], default='Any', max_length=11),
        ),
        migrations.AddField(
            model_name='monster',
            name='treasure',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specialability',
            name='shorthand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='attacks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='monstertype',
            name='monster_special_abilities',
        ),
        migrations.AlterField(
            model_name='specialability',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monstertype',
            name='monster_special_abilities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
