# Generated by Django 5.1.9 on 2025-08-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0025_remove_specialability_summary_monster_advancement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, unique=True)),
                ('subtype_special_abilities', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='special_abilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='fortitude',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('open', 'Undecided')], max_length=4),
        ),
        migrations.AlterField(
            model_name='monster',
            name='reflex',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('open', 'Undecided')], max_length=4),
        ),
        migrations.AlterField(
            model_name='monster',
            name='will',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('open', 'Undecided')], max_length=4),
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='fortitude',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('open', 'Undecided')], max_length=4),
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='reflex',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('open', 'Undecided')], max_length=4),
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='will',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('open', 'Undecided')], max_length=4),
        ),
    ]
