# Generated by Django 5.1.9 on 2025-08-12 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0026_monstersubtype_monster_special_abilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='bonus_hp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='deflection_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='reach',
            field=models.IntegerField(choices=[(-8, 'colossal'), (-4, 'gargantuan'), (-2, 'huge'), (-1, 'large'), (0, 'medium'), (1, 'small'), (2, 'tiny'), (4, 'diminutive'), (8, 'fine')], default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='crit_double',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='weapon',
            name='crit_range',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weapon',
            name='range_increment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='manufactured_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monster_armor', to='monsterbuilder.armor'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='shield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monster_shield', to='monsterbuilder.armor'),
        ),
    ]
