# Generated by Django 5.1.9 on 2025-08-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0027_monster_bonus_hp_monster_deflection_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='subtypes',
            field=models.ManyToManyField(blank=True, null=True, to='monsterbuilder.monstersubtype'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='double',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='reach',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='crit_double',
            field=models.CharField(default='✕2', max_length=5),
        ),
    ]
