# Generated by Django 5.1.9 on 2025-08-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0028_monster_subtypes_weapon_double_weapon_reach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='subtypes',
            field=models.ManyToManyField(to='monsterbuilder.monstersubtype'),
        ),
    ]
