# Generated by Django 5.1.9 on 2025-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0029_alter_monster_subtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='psionic_powers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='spells_at_will',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='spells_once_per_day',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='spells_once_per_week',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='spells_thrice_per_day',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='advancement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='alignment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='challenge_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monster_appearance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monster_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='plane',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='subtypes',
            field=models.ManyToManyField(blank=True, to='monsterbuilder.monstersubtype'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='treasure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='proficiency',
            field=models.CharField(choices=[('simple', 'Simple'), ('martial', 'Martial'), ('exotic', 'Exotic')], max_length=7),
        ),
    ]
