# Generated by Django 5.1.9 on 2025-08-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0030_monster_psionic_powers_monster_spells_at_will_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feat',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='monster',
            name='skills',
            field=models.ManyToManyField(blank=True, through='monsterbuilder.SkillRanks', to='monsterbuilder.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
