# Generated by Django 5.1.9 on 2025-08-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0031_alter_feat_name_alter_monster_skills_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialability',
            options={'verbose_name_plural': 'special abilities'},
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='double',
        ),
        migrations.AddField(
            model_name='skillranks',
            name='variant',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='max_dex',
            field=models.IntegerField(null=True, verbose_name='maximum dexterity bonus'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='crit_range',
            field=models.IntegerField(default=1, verbose_name='critical threat range'),
        ),
    ]
