# Generated by Django 5.1.9 on 2025-08-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0032_alter_specialability_options_remove_weapon_double_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='reach',
            field=models.IntegerField(default=5),
        ),
    ]
