# Generated by Django 5.1.9 on 2025-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0033_alter_monster_reach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialability',
            name='shorthand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
