# Generated by Django 5.1.9 on 2025-08-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0034_alter_specialability_shorthand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialability',
            name='save_ability',
        ),
        migrations.RemoveField(
            model_name='specialability',
            name='save_effect',
        ),
        migrations.RemoveField(
            model_name='specialability',
            name='save_type',
        ),
    ]
