# Generated by Django 5.1.9 on 2025-08-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterbuilder', '0035_remove_specialability_save_ability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='max_dex',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum dexterity bonus'),
        ),
    ]
