# Generated by Django 5.1.9 on 2025-05-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=18)),
                ('size', models.CharField(max_length=10)),
                ('HD_type', models.IntegerField()),
                ('HD_number', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('Fortitude', models.IntegerField()),
                ('Reflex', models.IntegerField()),
                ('Will', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('subtype', models.BooleanField()),
                ('good_fortitude', models.BooleanField()),
                ('good_reflex', models.BooleanField()),
                ('good_will', models.BooleanField()),
                ('skill_points', models.IntegerField()),
                ('proficiencies', models.TextField()),
                ('special_qualities', models.TextField()),
            ],
        ),
    ]
