# Generated by Django 5.1.9 on 2025-05-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_monster_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monster',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
